### ISSUE TITLE
Language setting

### ISSUE THREAD

**Issue by deftdawg** [ONLYOFFICE/plugin-languagetool#10]
1. It might be nice if the plugin defaulted to the language of the document, obviously `Auto` defaults to `US English`

    ![image](https://user-images.githubusercontent.com/4991612/144352865-b51e2c44-f07a-4a2b-9e0f-e899e782c79c.png)

2. `Auto` should should change to `Auto (US English)` or somewhere on the plugin UI there should be a label of what language the plugin thinks it's reading, so the user can know if they need to override it.

3. Some langauges are being shown twice in the dropdown

   ![image](https://user-images.githubusercontent.com/4991612/144353140-83f0aa2d-6a66-46c7-9f37-1b10b4b6ee38.png)

**Comment by Gingetsu** [comment]
Hello, @deftdawg .
Thank you for report, i can confirm - this is bug, issue 54455 and 54297 in our private issue tracker.

**Comment by trofim24** [comment]
Fixed
