### ISSUE TITLE
UI should highlight or select issues within the text

### ISSUE THREAD

**Issue by deftdawg** [ONLYOFFICE/plugin-languagetool#11]
![image](https://user-images.githubusercontent.com/4991612/144354116-a4896a56-2ab2-45a8-ac26-b132255e5239.png)

``This word has been used in one of the immediately preceding sentences`` 

**WHICH WORD** is this word?  It's not shown anywhere!

After I select an option the text changes and I have to look at it and try to figure out what exactly was replaced.  This is not a great user experince.

It would be much nicer, if when I clicked on an error to see the options the plugin automatically highlighted the text either in the plugin text box or in the document itself.   That way I could examine the error in context and understand whether the replacement makes sense or not... 

![image](https://user-images.githubusercontent.com/4991612/144354552-f400d0ba-f59b-4908-9bb2-17e7be37f252.png)

**Comment by deftdawg** [comment]
![image](https://user-images.githubusercontent.com/4991612/144355429-3809bde4-14f1-4fea-8470-0aaee97122a0.png)

Without showing the user which word is possibly mispelt, the this error serves no purpose.

**Comment by Gingetsu** [comment]
Hello, @deftdawg .
Thank you for report, I can confirm - this is bug, issue 49688 in our private issue tracker.

**Comment by rmeissn** [comment]
I've used the current develop branch to test the merged functionality. This feature is mandatory, works as expected and should be merged to master.

**Comment by Gingetsu** [comment]
Hello, @deftdawg . Our dev team is fixed your issue in next version  (But sorry, no exact ETA)
This fixed here: ONLYOFFICE/core@db2930e

**Comment by trofim24** [comment]
Fixed
