### ISSUE TITLE
portuguese dictionary

### ISSUE THREAD

**Issue by paulobreim** [ONLYOFFICE/plugin-languagetool#16]
Hello all
I am using onlyoffice and installed languagetool.
but where I can get and install dictionary for portuguese and english language?

tks
paulo

**Comment by ShockwaveNN** [comment]
Hi, could you clarify something for me?

This plugin uses API of https://languagetool.org/ service, so there is no possibility to install own languages

But I don't quite get - portuguese and english language is available:

![image](https://user-images.githubusercontent.com/668524/151510397-3e7fbdd9-cb2e-4cb5-9a22-a011fa04bbc3.png)

**Comment by paulobreim** [comment]
Yes, in the onlyoffice site show this plugin, but really I can't find dictionaries

**Comment by ShockwaveNN** [comment]
I'm sorry, I dont understand you

You've installed this plugin and cannot find Portuguese language in it?
Didn't my screenshot helped?

Please describe step by step what operations you've done and what do expect, because we may expect different things than you

**Comment by paulobreim** [comment]
Yes, I installed the plugin in the office and didnt find any language.

Here is the screens.
![Screenshot_20220129_160015](https://user-images.githubusercontent.com/381594/151674047-8abeb9e8-fbc0-405a-9067-33878f76ba5c.png)

![Screenshot_20220129_160045](https://user-images.githubusercontent.com/381594/151674053-fb3706fa-a6d8-475a-ad1a-4bc0b29768cb.png)

**Comment by ShockwaveNN** [comment]
I see that you've already closed this issue, but I think problem was that plugin sources was not the latest ones

**Comment by paulobreim** [comment]
no problem, it is not urgent.

**Comment by ShockwaveNN** [comment]
SO you still have problems? You shouldn't close this issue in that case

Could you attach plugin file? Seems that it's just old. You can compare it's internals (as zip archive) with this repo sources
