### ISSUE TITLE
Why don't you publish `.plugin` file?

### ISSUE THREAD

**Issue by bphd** [ONLYOFFICE/plugin-languagetool#17]

**Comment by ShockwaveNN** [comment]
Same as https://github.com/ONLYOFFICE/plugin-highlightcode/issues/37

Issue 55378 in our private issue tracker

**Comment by madmanRB** [comment]
I would love this too, just use LibreOffice for now as yeah installing this in OnlyOffice is rather hard and unintuitive.
I am very tech savvy yet for the life of me cannot find a way to install this, I read the instructions but they are useless.
It calls for a file called pluginCode.js and after unzipping the archive it is nowhere to be seen...

Let me guess i have to compile it, ugh.

**Comment by trofim24** [comment]
[Fixed](https://github.com/ONLYOFFICE/plugin-languagetool/releases/tag/v1.0.0)
