### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rmeissn** [ONLYOFFICE/plugin-languagetool#19]
I'd wanted to install this plugin at my flatpak installation of OnlyOffice. So I followed the manual steps and placed the content of this repository under `<user-home-dir>/.var/app/org.onlyoffice.desktopeditors/data/onlyoffice/desktopeditors/sdkjs-plugins`.
The plugin is shown in OnlyOffice, but without an icon. When I click on one of the two options, an error is displayed:
![Bildschirmfoto von 2022-02-10 13-35-23](https://user-images.githubusercontent.com/855967/153409697-9d0883c0-cea9-45f1-943b-deb77ce23152.png)

I read the installation documentation that tells me to move everything to the root plugin directory (instead of separate folders, like here on GitHub). This hasn't worked either and can't work, as e.g. some entries in config.json and other files are referencing these folders.

Is it possible to provide installation instructions?

**Comment by ShockwaveNN** [comment]
Could you attach plugin file?

Maybe this will help

https://api.onlyoffice.com/plugin/faq

**Comment by rmeissn** [comment]
Never mind, I've named the folder in the wrong way - forgot the "{}" around the hash.
It works now.

**Comment by rmeissn** [comment]
Just for completeness (Flatpak Install):
1. Navigate to `<user-home-dir>/.var/app/org.onlyoffice.desktopeditors/data/onlyoffice/desktopeditors/sdkjs-plugins` and create a folder which is named after the guid hash inside config.json (including the "{}") - so `{7CDB02C9-A0BF-4B56-9A1A-71C860B8498F}`
2. Open the created folder
4. Download this repository (optionally the develop branch) as a zip file to the previously created folder and extract the zip file there
5. Make sure that the guid named folder contains everything as shown [here](https://github.com/ONLYOFFICE/plugin-languagetool) - move files if the unzip process created only one folder, named after the zip file 
6. OPTIONAL: edit "scripts/langTool.js" to use a local instance of LanguageTool by replacing all 2 occurrences of `https://languagetool.org/api/` with e.g. `http://localhost:8081/`
7. Restart OnlyOffice and look for the plugin at the plugins tab
