### ISSUE TITLE
why is it so hard to install this plugin?

### ISSUE THREAD

**Issue by madmanRB** [ONLYOFFICE/plugin-languagetool#21]
Look I am not an idiot, I complained that the .zip on github doesnt have the required pluginCode.js that you need to create the .plugin.
Where is it? In the bloody crab nebula?
Do I need to compile it?
Ugh, installing it in LibreOffice is 100000X easier.

**Comment by ShockwaveNN** [comment]
Hi

>  I complained that the .zip on github doesnt have the required pluginCode.js

Could you point out instruction there is this phrase used, seems this should be fixed

And I think most of your question can be answered with [this page](https://api.onlyoffice.com/plugin/faq)

**Comment by madmanRB** [comment]
I read the documentation, I looked at videos.
I am not an idiot.

**Comment by ShockwaveNN** [comment]
Could you attach file you've got?

**Comment by madmanRB** [comment]
its the same .zip I got from here, from this very github

**Comment by madmanRB** [comment]
[plugin-languagetool-master.zip](https://github.com/ONLYOFFICE/plugin-languagetool/files/8699214/plugin-languagetool-master.zip)

**Comment by madmanRB** [comment]
Again did everytyhing on the instuctions:
Step 1 download the .zip and change the file to a .plugin file: Check
Step 2 Click the Settings button on the Plugins tab: Check
Step 3  In the plugin Settings window, click the Add plugin button to load your created archive: Check

I mean it sounds easy right?
What in the hell am I missing!?
Why doesnt this piece of $#!T work?

**Comment by ShockwaveNN** [comment]
You should check [this ](https://api.onlyoffice.com/plugin/faq) page again - 

this part:

> I packed the plugin folder to the archive, changed its extension to .plugin and added it to the editors. But it doesn’t work. What should I do?

Correct plugin file will like that:
[languagetools.zip](https://github.com/ONLYOFFICE/plugin-languagetool/files/8699256/languagetools.zip)
(change extension from zip to `plugin`)

**Comment by madmanRB** [comment]
I read that part and I thought thats what I did when I tried to do it on my own.
I mean I did extract it, and re zip it into its own archive thinking that was the problem.
I am using windows and peazip to extract it, should I have used the 7zip extractor?

**Comment by ShockwaveNN** [comment]
I don't think extractor has meaning in this context
> Step 1 download the .zip and change the file to a .plugin file: Check

This is not enough, you should repack files downloaded from repo

So just use my file, it should work fine

**Comment by madmanRB** [comment]
You mean the source files?
I mean if this was Linux sure Git is easy to do, and maybe I could do that with git under WSL but thats an extra step for the average windows user.
I will just use that prepackaged file, wish I had that a few hours ago...

**Comment by ShockwaveNN** [comment]
I agree with you that already packaged files will be easier to use

We got issue https://github.com/ONLYOFFICE/plugin-languagetool/issues/17 about that, but currently it's not implemented

**Comment by catbasilio** [comment]
Fixed
