### ISSUE TITLE
Empty master branch

### ISSUE THREAD

**Issue by rmnwnsx** [ONLYOFFICE/plugin-languagetool#3]
Is there only dev Version of the plugin, or has someone forgotten to merge it with master?

**Comment by ShockwaveNN** [comment]
Master branch is empty because in current state `plugin-languagetool` is not ready for public release and in still not problem fixed\or checked

**Comment by rmnwnsx** [comment]
> Master branch is empty because in current state `plugin-languagetool` is not ready for public release and in still not problem fixed\or checked

Ok, I understand. Because I just thought that something go wrong. Thank you!
