### ISSUE TITLE
v2 Error

### ISSUE THREAD

**Issue by thunderclap82** [ONLYOFFICE/plugin-languagetool#5]
I'm running OnlyOffice in a docker on Unraid and have installed this plugin in the sdkjs-plugins directory. When I try to run the plugin I get the following error:

`Error: You have '/v2/' in your path, but not at the root. Try an URL like 'http://server/v2/...'`

I also have an instance of LanguageTool installed on my server in another docker and have tried changing the URL in the langTool.js script to point to that subdomain but the error still shows. Any ideas how to get it working? Thanks.

**Comment by ShockwaveNN** [comment]
Is this problem actual only for `languagetool` plugin or any other

I don't think we have Unraid in our access, could you try to repoduce it with native docker setup (on Ubuntu for example)?

**Comment by thunderclap82** [comment]
Wow, that was a much faster response than I expected. Thank you.

As an experiment I removed the docker I was using and tried a different, newer, one. The error went away and it looks like it works now. If anything changes I'll be sure to let you know. Thanks again.

**Comment by ovizii** [comment]
I also had the same problem with this image: https://github.com/Erikvl87/docker-languagetool so I changed the URLs to:

https://languagetool.org/v2/check

omitting the “API” part, and it's all working now. Just commenting here in case someone else has the same problem.
