### ISSUE TITLE
 Installation process problem

### ISSUE THREAD

**Issue by renanwp2** [ONLYOFFICE/plugin-languagetool#6]
I have tried to change the change .zip file extension to .plugin, and tried to add the plugin to OnlyOffice, but It seems not to work. I think an installation process guide exclusively to the LanguageTool would solve a lot of issues. Beyond I have done, what is needed more?

**Comment by ShockwaveNN** [comment]
I think your plugin is incorrectly formed, do you read [this FAQ](https://api.onlyoffice.com/plugin/faq#plugins_6) entry

If this does not help - please attach your `.plugin` file to this issue

**Comment by renanwp2** [comment]
Hi,

I was able to install the package copying the app to the right directory in Linux. Basically, a installed systemwise. 

Renan W. P.

**Comment by ShockwaveNN** [comment]
Am I right that your issue is resolved now?

If so I'm closing this issue
